require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tunnels", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Tunnel. As you add validations to Tunnel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tunnel.create! valid_attributes
      get tunnels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tunnel = Tunnel.create! valid_attributes
      get tunnel_url(tunnel)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tunnel_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tunnel = Tunnel.create! valid_attributes
      get edit_tunnel_url(tunnel)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tunnel" do
        expect {
          post tunnels_url, params: { tunnel: valid_attributes }
        }.to change(Tunnel, :count).by(1)
      end

      it "redirects to the created tunnel" do
        post tunnels_url, params: { tunnel: valid_attributes }
        expect(response).to redirect_to(tunnel_url(Tunnel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tunnel" do
        expect {
          post tunnels_url, params: { tunnel: invalid_attributes }
        }.to change(Tunnel, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tunnels_url, params: { tunnel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tunnel" do
        tunnel = Tunnel.create! valid_attributes
        patch tunnel_url(tunnel), params: { tunnel: new_attributes }
        tunnel.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tunnel" do
        tunnel = Tunnel.create! valid_attributes
        patch tunnel_url(tunnel), params: { tunnel: new_attributes }
        tunnel.reload
        expect(response).to redirect_to(tunnel_url(tunnel))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tunnel = Tunnel.create! valid_attributes
        patch tunnel_url(tunnel), params: { tunnel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tunnel" do
      tunnel = Tunnel.create! valid_attributes
      expect {
        delete tunnel_url(tunnel)
      }.to change(Tunnel, :count).by(-1)
    end

    it "redirects to the tunnels list" do
      tunnel = Tunnel.create! valid_attributes
      delete tunnel_url(tunnel)
      expect(response).to redirect_to(tunnels_url)
    end
  end
end
